// The pure parts of the Aseprite round-trip: baking an element out of the
// game into an image, and turning an image back into a src/art module.
import type { ArtData } from "../src/scene/art.ts";
import type { Pixels } from "../src/scene/pixels.ts";
import type { Image } from "./png.ts";

/** Palette characters for generated art (no ".", quotes or backslashes). */
const CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#%&*+-/:;<=>?@[]^_{|}~()$,";

/**
 * Crop a rendered element to an image whose bottom-centre pixel is the
 * element's anchor (cx, bottom), so it can be drawn back in the same place.
 */
export function cropToAnchor(px: Pixels, cx: number, bottom: number): Image {
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  for (let y = 0; y <= Math.min(bottom, px.height - 1); y++) {
    for (let x = 0; x < px.width; x++) {
      if (px.data[y * px.width + x]! >>> 24) {
        minX = Math.min(minX, x);
        maxX = Math.max(maxX, x);
        minY = Math.min(minY, y);
      }
    }
  }
  if (minX === Infinity) throw new Error("Nothing was drawn for this element");
  const half = Math.max(cx - minX, maxX - cx);
  const width = half * 2 + 1;
  const height = bottom - minY + 1;
  const rgba = new Uint8Array(width * height * 4);
  const bytes = new Uint8Array(px.data.buffer);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const sx = cx - half + x;
      const sy = minY + y;
      if (sx < 0 || sx >= px.width || sy < 0 || sy >= px.height) continue;
      const src = (sy * px.width + sx) * 4;
      rgba.set(bytes.subarray(src, src + 4), (y * width + x) * 4);
    }
  }
  return { width, height, rgba };
}

/** Image → palette rows. Pixels under half opacity count as transparent. */
export function toArtData({ width, height, rgba }: Image): ArtData {
  const palette: Record<string, string> = {};
  const byColor = new Map<string, string>();
  const rows: string[] = [];
  for (let y = 0; y < height; y++) {
    let row = "";
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      if (rgba[i + 3]! < 128) {
        row += ".";
        continue;
      }
      const color = `#${[rgba[i]!, rgba[i + 1]!, rgba[i + 2]!].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
      let key = byColor.get(color);
      if (!key) {
        key = CHARS[byColor.size];
        if (!key) throw new Error(`Too many colours (max ${CHARS.length}). Try reducing the palette in Aseprite.`);
        byColor.set(color, key);
        palette[key] = color;
      }
      row += key;
    }
    rows.push(row);
  }
  return { w: width, h: height, palette, rows };
}

/** The source of a generated src/art/<id>.ts module. */
export function artModule(id: string, data: ArtData): string {
  return `// Generated from art/${id}.png by \`bun run art\`. Edit the art, not this file.
import type { ArtData } from "../scene/art.ts";

const art: ArtData = ${JSON.stringify(data, null, 2)};

export default art;
`;
}

/** The source of src/art/index.ts, registering every generated module. */
export function indexModule(ids: string[]): string {
  const sorted = [...ids].sort();
  const name = (id: string) => `art_${id.replace(/[^a-zA-Z0-9]/g, "_")}`;
  return `// Generated by \`bun run art\` from art/*.png. Don't edit by hand.
import type { ArtData } from "../scene/art.ts";
${sorted.map((id) => `import ${name(id)} from "./${id}.ts";`).join("\n")}

export const ART_DATA: Record<string, ArtData> = {${sorted.map((id) => `\n  "${id}": ${name(id)},`).join("")}${sorted.length ? "\n" : ""}};
`;
}
